name: Mathics (Windows)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2016
    strategy:
      matrix:
        os: [windows]
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        choco install llvm
        set LLVM_DIR="C:\Program Files\LLVM"
        pip install llvmlite
        pip install numpy
        pip install sympy
        pip install pillow
        pip install scikit-image
        pip install requests
        pip install wordcloud
        pip install PyYAML
        pip install palettable
        pip install mpmath
        pip install mathics_scanner
    - name: Install Mathics
      run: |
        python setup.py install
    - name: Test Mathics
      run: |
        pip install pytest pexpect
        make check
